# Vector configuration optimized for 10K logs/sec
# Sources
[sources.file_logs]
type = "file"
include = ["/shared-logs/aiscout.log"]
read_from = "beginning"
start_at_beginning = true

# Transforms
[transforms.parse_json]
type = "remap"
inputs = ["file_logs"]
source = '''
  . = parse_json!(string!(.message)) ?? .
'''

# Elasticsearch sink optimized for high throughput
[sinks.elasticsearch]
type = "elasticsearch"
inputs = ["parse_json"]
endpoints = ["https://elasticsearch:9200"]
index = "vector-logs-%Y.%m.%d"
mode = "bulk"
compression = "none"

# High-throughput bulk settings
bulk.max_events = 5000
bulk.timeout_secs = 0.1
bulk.max_bytes = 10485760

# High-concurrency HTTP settings
request.concurrency = "adaptive"
request.in_flight_limit = 16
request.retry_attempts = 3
request.timeout_secs = 30

# TLS settings
tls.verify_certificate = false
tls.verify_hostname = false

# Authentication
auth.strategy = "basic"
auth.user = "elastic"
auth.password = "changeme"

# Health check
healthcheck.enabled = true

# API settings
[api]
enabled = false

# Buffer settings for high throughput
buffer.type = "memory"
buffer.max_events = 50000
buffer.when_full = "block"
